-- MySQL 初始化脚本
-- 创建数据库
CREATE DATABASE IF NOT EXISTS flashsale_user DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS flashsale_activity DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS flashsale_inventory DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS flashsale_order DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS nacos_config DEFAULT CHARSET utf8mb4;

-- 创建用户（如果需要）
-- CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'root';
-- GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
-- FLUSH PRIVILEGES;
